# Generated by Django 6.0 on 2026-01-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_payment_checkout_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
