# Generated by Django 6.0 on 2026-01-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_checkout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
