# Generated by Django 6.0 on 2026-01-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_ticket_order'),
        ('users', '0006_alter_customuser_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
