# Generated by Django 6.0 on 2025-12-31 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data_of_create', models.DateField()),
                ('slogan', models.CharField(max_length=200)),
                ('airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Airports.airports')),
            ],
        ),
        migrations.CreateModel(
            name='Airplanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('count_of_seats', models.IntegerField()),
                ('airlines', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airplanes.airlines')),
            ],
        ),
    ]
