# Generated by Django 6.0 on 2026-01-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('detail', models.TextField()),
                ('data_of_create', models.DateField(auto_now_add=True)),
                ('slogan', models.CharField(max_length=200)),
                ('airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airlines', to='airports.airports')),
            ],
        ),
        migrations.CreateModel(
            name='Airplanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('economy_class_seats', models.PositiveSmallIntegerField(default=0)),
                ('business_class_seats', models.PositiveSmallIntegerField(default=0)),
                ('first_class_seats', models.PositiveSmallIntegerField(default=0)),
                ('airlines', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airplanes', to='airplanes.airlines')),
            ],
        ),
    ]
