# Generated by Django 6.0 on 2026-01-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlines',
            name='data_of_create',
            field=models.DateField(),
        ),
    ]
