# Generated by Django 6.0 on 2025-12-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlines',
            name='detail',
            field=models.TextField(default='Not info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airplanes',
            name='count_of_seats',
            field=models.PositiveIntegerField(),
        ),
    ]
