services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db

  celery:
    build: .
    command: celery -A Project worker -l info --max-tasks-per-child=1000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_HOST=db

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http web:8000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data: