# Generated by Django 6.0 on 2026-01-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('city_departure', models.CharField(max_length=100)),
                ('city_arrival', models.CharField(max_length=100)),
                ('time_departure', models.DateTimeField()),
                ('time_arrival', models.DateTimeField()),
                ('tickets_count', models.PositiveSmallIntegerField()),
                ('airplanes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airplanes.airplanes')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_class', models.CharField(choices=[('econom', 'Econom class'), ('business', 'Business class'), ('first', 'First class')], default='econom', max_length=20)),
                ('time_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flights.flights')),
            ],
        ),
    ]
