# Generated by Django 6.0 on 2025-12-31 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_departure', models.CharField(max_length=100)),
                ('country_arrival', models.CharField(max_length=100)),
                ('time_departure', models.DateTimeField()),
                ('time_arrival', models.DateTimeField()),
                ('tickets_count', models.IntegerField()),
                ('airplanes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airplanes.airplanes')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_class', models.CharField(choices=[('econom', 'Низький клас'), ('business', 'Бізнес клас'), ('first', 'Перший клас')], default='econom', max_length=20)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flights.flights')),
            ],
        ),
    ]
