# Generated by Django 6.0 on 2026-01-05 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airplanes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_status', models.CharField(choices=[('scheduled', 'Запланований'), ('boarding', 'Посадка'), ('departed', 'Вилетів'), ('delayed', 'Затриманий'), ('cancelled', 'Відмінений')], default='scheduled', max_length=20)),
                ('city_departure', models.CharField(max_length=100)),
                ('city_arrival', models.CharField(max_length=100)),
                ('time_departure', models.DateTimeField()),
                ('time_arrival', models.DateTimeField()),
                ('tickets_count', models.PositiveSmallIntegerField()),
                ('airplanes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airplanes.airplanes')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_class', models.CharField(choices=[('econom', 'Низький клас'), ('business', 'Бізнес клас'), ('first', 'Перший клас')], default='econom', max_length=20)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flights.flights')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
