# Generated by Django 6.0 on 2026-01-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('city_departure', models.CharField(max_length=100)),
                ('city_arrival', models.CharField(max_length=100)),
                ('time_departure', models.DateTimeField()),
                ('time_arrival', models.DateTimeField()),
                ('tickets_count_economy', models.PositiveSmallIntegerField(default=0)),
                ('tickets_count_business', models.PositiveSmallIntegerField(default=0)),
                ('tickets_count_first', models.PositiveSmallIntegerField(default=0)),
                ('ticket_economy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket_business_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket_first_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airplanes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airplanes.airplanes')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First')], default='economy', max_length=20)),
                ('seat_number', models.PositiveIntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flights.flights')),
            ],
        ),
    ]
