# Generated by Django 6.0 on 2025-12-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='tickets_count',
            field=models.PositiveIntegerField(),
        ),
    ]
