# Generated by Django 6.0 on 2026-01-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='flight_status',
            field=models.CharField(choices=[('scheduled', 'Запланований'), ('boarding', 'Посадка'), ('departed', 'Вилетів'), ('delayed', 'Затриманий'), ('cancelled', 'Відмінений')], default='scheduled', max_length=20),
        ),
    ]
