# Generated by Django 6.0 on 2025-12-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0002_alter_flights_tickets_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='country_arrival',
            new_name='city_arrival',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='country_departure',
            new_name='city_departure',
        ),
    ]
