# Generated by Django 6.0 on 2025-12-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airports',
            name='title',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
    ]
