# Generated by Django 6.0 on 2025-12-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airports', '0002_airports_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='airports',
            name='address',
            field=models.CharField(default='Not info', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airports',
            name='contact',
            field=models.CharField(default='Not info', max_length=200),
            preserve_default=False,
        ),
    ]
