# Generated by Django 6.0 on 2026-01-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_alter_geminichatsession_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geminichatsession',
            name='model_name',
            field=models.CharField(choices=[('gemini-1.5-flash-002', 'Gemini 1.5 Flash'), ('gemini-3-flash-preview', 'Gemini 3 Flash Preview'), ('gemini-3-pro-preview', 'Gemini 3 Pro Preview'), ('gemini-2.5-flash', 'Gemini 2 5 Flash')], default='gemini-1.5-flash-002', max_length=50),
        ),
    ]
