# Generated by Django 6.0 on 2026-01-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_alter_geminichatsession_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geminichatsession',
            name='model_name',
            field=models.CharField(choices=[('gemini-2.0-flash-lite', 'Gemini 2.0 Flash Lite'), ('gemini-3-flash-preview', 'Gemini 3 Flash Preview'), ('gemini-3-pro-preview', 'Gemini 3 Pro Preview'), ('gemini-2.5-flash', 'Gemini 2 5 Flash')], default='gemini-2.0-flash-lite', max_length=50),
        ),
    ]
