# Generated by Django 6.0 on 2026-01-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_alter_geminichatsession_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geminichatsession',
            name='model_name',
            field=models.CharField(choices=[('gemini-3-flash-preview', 'Gemini 3 Flash'), ('gemini-2.5-flash', 'Gemini 2 5 Flash'), ('gemini-2.5-flash-lite', 'Gemini 2 5 Flash Lite')], default='gemini-2.5-flash-lite', max_length=50),
        ),
    ]
